### PR TITLE
Bump diesel to 2.2

### PR DESCRIPTION
**Pull request by weiznich**

### CODE REVIEW

**Comment by McDic** [comment]
Just curious, is there any plan to officially maintain this crate from `diesel.rs` organization?

**Comment by Swaagie** [comment]
For what it is worth was able to verify this branch works with 2.2 and limited use of geometry features.

**Comment by weiznich** [comment]
@McDic I still consider this not on par with diesel itself due to missing language features. See [this post](https://blog.weiznich.de/blog/async-transaction-problem/) for a long version of the underlying problem. I would like to keep that separate as long as the language level problem is not resolved to avoid people thinking that this is a perfect solution. (To be clear hear that problem also appears for all the other async interfaces.)

**Comment by dullbananas** [comment]
I want this change to be released soon

**Comment by weiznich** [comment]
@dullbananas We all want to do that, but there are still blocking issues (like #103 ) that need to be resolved first. Just requesting a release won't make that happen faster, but instead it will take time away that could be spend on working on these issues. Your contributions are welcome there.

**Pull request merged**
