### PR TITLE
Update `deadpool` to `0.11`

### PR DESCRIPTION
**Pull request by jun-sheaf**

### CODE REVIEW

**Review by weiznich — COMMENTED** [review]
Thanks for opening this PR. I think it looks good overall :+1:

The CI failures are unrelated to this PR. They are caused by github updating the macro runner to default to the arm variants, which means we need a slightly different setup part for these jobs. I will try to address that in the next days.

**Review by weiznich — APPROVED** [review]

**Comment by jun-sheaf** [comment]
@weiznich I don't have write access. Can you merge?

**Comment by weiznich** [comment]
It will be merged as soon as I had time to fix the CI.

**Comment by jun-sheaf** [comment]
@weiznich Thanks for merging! Do you think you can create a release?

**Comment by weiznich** [comment]
@jun-sheaf That's currently blocked on a diesel release (as the master branch depends on unreleased diesel features) and on fixing #103. I cannot comment on when this will be done as I'm currently only work on this project in my free time. Contributions to make either of the required prerequisites happening faster are always welcome.

**Pull request merged**
